net/xfrm: fix unused variable caused by previous merge
../../../../../../kernel/samsung/m30s-common/net/xfrm/xfrm_policy.c:48:42: error: unused variable 'xfrm_last_dst' [-Werror,-Wunused-variable]
static DEFINE_PER_CPU(struct xfrm_dst *, xfrm_last_dst);
                                         ^
../../../../../../kernel/samsung/m30s-common/net/xfrm/xfrm_policy.c:49:28: error: unused variable 'xfrm_pcpu_work' [-Werror,-Wunused-variable]
static struct work_struct *xfrm_pcpu_work __read_mostly;
                           ^
2 errors generated.